#!/usr/bin/env bash
# research-sdd-init.test.sh — RED-FIRST regression harness for research-sdd-init.sh.
#
# These fixtures back the scaffolder's SAFETY CLAIMS (never clobber, never duplicate,
# fail loud, don't corrupt the user's .gitignore) — not just the happy path. An earlier
# version of this suite was theater: it passed while three real data-loss/duplication/
# silent-failure defects were present (two fresh-context reviews caught them). Each BAD
# fixture below reproduces one of those and asserts the scaffolder REFUSES or ABORTS.
# --prove-teeth mutates the corpus-present guard and asserts a data-loss fixture then
# clobbers — proving the refuse tests depend on the guard.
#
# Usage: research-sdd-init.test.sh [--prove-teeth]      Exit: 0 = all held · 1 = regression.

set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SUT="$HERE/../research-sdd-init.sh"
[ -f "$SUT" ] || { echo "FATAL: SUT not found: $SUT" >&2; exit 2; }
TMP="$(mktemp -d)"; trap 'chmod -R u+w "$TMP" 2>/dev/null; rm -rf "$TMP"' EXIT
pass=0; fail=0
ok() { printf '  PASS  %s\n' "$1"; pass=$((pass+1)); }
no() { printf '  FAIL  %s\n' "$1"; fail=$((fail+1)); }
assert_exit()   { local w="$1" l="$2"; shift 2; local g; bash "$SUT" "$@" >/dev/null 2>&1; g=$?; [ "$g" = "$w" ] && ok "$l (exit $g)" || no "$l — expected $w, got $g"; }
assert_file()   { [ -f "$2" ] && ok "$1" || no "$1 (missing: $2)"; }
assert_absent() { [ ! -e "$2" ] && ok "$1" || no "$1 (should NOT exist: $2)"; }
assert_grep()   { grep -qF "$2" "$3" 2>/dev/null && ok "$1" || no "$1 (pattern '$2' not in $3)"; }

echo "== research-sdd-init.test.sh (SUT: $(basename "$SUT")) =="

# GOOD 1 — flat scaffold on an empty target → full skeleton at root
d="$TMP/good-flat"; mkdir -p "$d"
assert_exit 0 "GOOD flat: scaffolds empty target" "$d" --corpus flat
for f in INDEX.md RESEARCH-STATE.md sources/SOURCES.md .claude/hooks/research-protocol.sh; do
  assert_file "  flat: $f" "$d/$f"
done
# eje #2 — NO per-target gen-catalog.py copy is seeded (the drift source is eliminated; CATALOG.md is
# regenerated by research-sdd-archive.sh via the kit generator). Pin that init does NOT scaffold it.
assert_absent "  flat: NO per-target tools/gen-catalog.py (eje #2)" "$d/tools/gen-catalog.py"
[ -d "$d/retros" ] && ok "  flat: retros/ at target root" || no "  flat: retros/ at target root"
assert_grep "  flat: .gitignore has .atl/"    ".atl/"    "$d/.gitignore"
assert_grep "  flat: .gitignore has .claude/" ".claude/" "$d/.gitignore"
[ -d "$d/.git" ] && ok "  flat: git initialized" || no "  flat: git initialized"
# kit-sup #5: tools/ provenance ledger seeded at target root (distinct from eje #2 gen-catalog.py drift)
assert_file "  flat: tools/README.md seeded"                     "$d/tools/README.md"
[ -s "$d/tools/README.md" ] && ok "  flat: tools/README.md non-empty (anti-silent-zero)" \
  || no "  flat: tools/README.md is empty or missing (anti-silent-zero)"
assert_grep "  flat: tools/README.md is a provenance ledger"     "Provenance" "$d/tools/README.md"

# GOOD 2 — auto nests when subject material is present; root stays clean
d="$TMP/good-nested"; mkdir -p "$d"; : > "$d/app.html"
assert_exit 0 "GOOD auto: nests on subject material" "$d" --corpus auto
assert_file   "  nested: corpus/INDEX.md"     "$d/corpus/INDEX.md"
assert_absent "  nested: NO root INDEX.md"    "$d/INDEX.md"
[ -d "$d/retros" ] && ok "  nested: retros/ at target root" || no "  nested: retros/ at root"
# kit-sup #5: tools/ at TARGET root (not corpus subdir) in nested layout
assert_file   "  nested: tools/README.md at target root"     "$d/tools/README.md"
assert_absent "  nested: NO tools/ under corpus/"            "$d/corpus/tools/README.md"

# GOOD 3 — auto on empty target → flat
d="$TMP/good-auto-empty"; mkdir -p "$d"
assert_exit 0 "GOOD auto: flat when empty" "$d" --corpus auto
assert_file "  auto-empty: root INDEX.md" "$d/INDEX.md"

# GOOD 4 — auto sees a HIDDEN subject file (dotglob) → nests
d="$TMP/good-dotfile"; mkdir -p "$d"; : > "$d/.env"
assert_exit 0 "GOOD auto: nests on a hidden subject file" "$d" --corpus auto
assert_file "  dotfile: corpus/INDEX.md" "$d/corpus/INDEX.md"

# GOOD 5 — auto on a dir whose only entry is .git/ (infra, skip-listed) → flat
d="$TMP/good-onlygit"; mkdir -p "$d/.git"
assert_exit 0 "GOOD auto: flat when only .git present" "$d" --corpus auto
assert_file "  onlygit: root INDEX.md" "$d/INDEX.md"

# BAD 1 — refuse over an existing INDEX
d="$TMP/bad-index"; mkdir -p "$d"; printf 'SENTINEL\n' > "$d/INDEX.md"
assert_exit 3 "BAD: refuses over existing INDEX.md" "$d" --corpus flat
assert_grep "  refuse: INDEX untouched" "SENTINEL" "$d/INDEX.md"

# BAD 2 (DATA-LOSS) — INDEX deleted but RESEARCH-STATE holds real curated data → must refuse, not clobber
d="$TMP/bad-dataloss"; mkdir -p "$d"; printf 'REAL HAND-CURATED GAPS\n' > "$d/RESEARCH-STATE.md"
assert_exit 3 "BAD: refuses when only RESEARCH-STATE exists (data-loss)" "$d" --corpus flat
assert_grep "  data-loss: RESEARCH-STATE untouched" "REAL HAND-CURATED GAPS" "$d/RESEARCH-STATE.md"

# BAD 3 (DUPLICATION) — a nested corpus exists; auto must NOT scaffold a second flat one
d="$TMP/bad-dup"; mkdir -p "$d/corpus" "$d/retros"; printf 'REAL NESTED CORPUS\n' > "$d/corpus/INDEX.md"
assert_exit 3 "BAD: refuses to duplicate an existing nested corpus" "$d" --corpus auto
assert_absent "  dup: NO second root INDEX.md" "$d/INDEX.md"
assert_grep   "  dup: nested corpus untouched" "REAL NESTED CORPUS" "$d/corpus/INDEX.md"

# BAD 4 (SILENT FAILURE) — read-only target → FATAL exit 2, tree left empty
# Also pins that the SUT's own writability probe fired (not an incidental downstream mkdir failure).
d="$TMP/bad-readonly"; mkdir -p "$d"; chmod 555 "$d"
ro_stderr="$(bash "$SUT" "$d" --corpus flat 2>&1 1>/dev/null)"
assert_exit 2 "BAD: read-only target fails loud (exit 2)" "$d" --corpus flat
assert_absent "  readonly: no INDEX created" "$d/INDEX.md"
grep -q "not writable" <<< "$ro_stderr" \
  && ok "  readonly: SUT's own writability probe fired ('not writable' in stderr)" \
  || no "  readonly: SUT's writability probe DID NOT fire (no 'not writable' in stderr)"
chmod u+w "$d"

# BAD 5 — nonexistent target dir
assert_exit 2 "BAD: nonexistent target dir" "$TMP/does-not-exist" --corpus flat

# GITIGNORE 6 — pre-existing .gitignore with NO trailing newline must not fuse
d="$TMP/gi-nonewline"; mkdir -p "$d"; printf 'node_modules/' > "$d/.gitignore"   # no trailing \n
assert_exit 0 "GITIGNORE: appends without fusing the last line" "$d" --corpus flat
assert_grep "  gitignore: node_modules/ intact on its own line" "node_modules/" "$d/.gitignore"
grep -qxF 'node_modules/' "$d/.gitignore" && ok "  gitignore: node_modules/ not fused" || no "  gitignore: node_modules/ FUSED with next pattern"

# ROLLBACK 7 — a template fails mid-scaffold → clean up what THIS run created, leave NO partial tree
# PRECIOUS.md is pre-existing: rollback must NOT delete it (data-loss guard).
# A mutant rollback doing rm -rf "$target"/* would destroy PRECIOUS.md while the absence
# assertions all still pass — this sentinel makes the over-deletion visible (proven below).
cp -r "$HERE/../../templates" "$TMP/rbk-templates"
mkdir -p "$TMP/rbk/toolbelt"; cp "$SUT" "$TMP/rbk/toolbelt/init.sh"; ln -sfn "$TMP/rbk-templates" "$TMP/rbk/templates"
chmod 000 "$TMP/rbk-templates/RESEARCH-STATE.template.md"   # 2nd cp fails after INDEX is copied
d="$TMP/rollback"; mkdir -p "$d"
printf 'PRECIOUS\n' > "$d/PRECIOUS.md"    # pre-existing file this run did NOT create
bash "$TMP/rbk/toolbelt/init.sh" "$d" --corpus flat >/dev/null 2>&1; rc=$?
[ "$rc" != 0 ] && ok "ROLLBACK: mid-scaffold failure exits non-zero (exit $rc)" || no "ROLLBACK: mid-scaffold failure exited 0"
assert_absent "  rollback: partial INDEX.md removed" "$d/INDEX.md"
assert_absent "  rollback: partial tools/ removed"   "$d/tools"
assert_absent "  rollback: no orphaned .claude/"     "$d/.claude"
assert_absent "  rollback: no orphaned retros/"      "$d/retros"
# sentinel must survive intact — rollback is scoped to what THIS run created
[ -f "$d/PRECIOUS.md" ] && ok "  rollback: sentinel PRECIOUS.md survived (rollback is scoped)" \
  || no "  rollback: sentinel PRECIOUS.md was DELETED — rollback over-deleted (DATA LOSS BUG)"
grep -qxF 'PRECIOUS' "$d/PRECIOUS.md" 2>/dev/null \
  && ok "  rollback: sentinel content unchanged (bytes intact)" \
  || no "  rollback: sentinel content corrupted or missing"
# only the sentinel must remain — no scaffold artifacts left behind
leftover="$(find "$d" -maxdepth 1 -mindepth 1 ! -name 'PRECIOUS.md' 2>/dev/null)"
[ -z "$leftover" ] && ok "  rollback: only sentinel remains (no scaffold artifacts)" \
  || no "  rollback: unexpected entries alongside sentinel: $leftover"
chmod u+w "$TMP/rbk-templates/RESEARCH-STATE.template.md"

# --force overrides the refuse
d="$TMP/force"; mkdir -p "$d"; printf 'SENTINEL\n' > "$d/INDEX.md"
assert_exit 0 "--force re-scaffolds over existing" "$d" --corpus flat --force

# --- Item 1: PROMPT-LOOP cross-references (stdout capture, no-prefix run) ---
d="$TMP/xref"; mkdir -p "$d"
bash "$SUT" "$d" --corpus flat > "$TMP/xref.out" 2>/dev/null
assert_grep "xref: step-1 has PROMPT-LOOP §b)" "PROMPT-LOOP §b)" "$TMP/xref.out"
assert_grep "xref: step-3 has §e)" "§e)" "$TMP/xref.out"
assert_grep "xref: step-4 has §c follow-up)" "§c follow-up)" "$TMP/xref.out"

# --- Item 1: step-5 conditional transparency ---
d="$TMP/nopfx"; mkdir -p "$d"
bash "$SUT" "$d" --corpus flat > "$TMP/nopfx.out" 2>/dev/null
assert_grep "step-5 note present in no-prefix run" "no --prefix given" "$TMP/nopfx.out"
if grep -qF "5. Block files use the prefix:" "$TMP/nopfx.out" 2>/dev/null; then
  no "step-5 absent in no-prefix run"
else
  ok "step-5 absent in no-prefix run"
fi
d="$TMP/pfx"; mkdir -p "$d"
bash "$SUT" "$d" --corpus flat --prefix foo > "$TMP/pfx.out" 2>/dev/null
assert_grep "step-5 present in prefix run" "5. Block files use the prefix: foo-blockN.md" "$TMP/pfx.out"
if grep -qF "no --prefix given" "$TMP/pfx.out" 2>/dev/null; then
  no "no-prefix note absent in prefix run"
else
  ok "no-prefix note absent in prefix run"
fi

# --- Item 2: already-git split message (dynamic $TMP fixture, never tests/fixtures/) ---
if ! command -v git >/dev/null 2>&1; then
  echo "  SKIP  already-git: git not on PATH"
else
  d="$TMP/already-git"; mkdir -p "$d"; git -C "$d" init -q 2>/dev/null
  bash "$SUT" "$d" --corpus flat > "$TMP/agit.out" 2>/dev/null
  assert_grep "already-git: corpus files land untracked" "corpus files land untracked" "$TMP/agit.out"
  assert_grep "already-git: .claude/ hook is gitignored" ".claude/ hook is gitignored" "$TMP/agit.out"
  assert_grep "already-git: git add --force mentioned" "git add --force" "$TMP/agit.out"
fi

# --- Item 3: NEXT next-step pointer and BOOTSTRAP mental model ---
d="$TMP/nextstep"; mkdir -p "$d"
bash "$SUT" "$d" --corpus flat > "$TMP/nextstep.out" 2>/dev/null
assert_grep "next-step: research-sdd-status.sh pointer" "research-sdd-status.sh" "$TMP/nextstep.out"
assert_grep "next-step: BOOTSTRAP in next-step section" "BOOTSTRAP" "$TMP/nextstep.out"

# NEGATIVE CONTROL — prove the corpus-present guard has TEETH.
if [ "${1:-}" = "--prove-teeth" ]; then
  echo "-- teeth proof: neuter the corpus-present guard, expect the data-loss fixture to CLOBBER --"
  mkdir -p "$TMP/mk/toolbelt"; ln -sfn "$HERE/../../templates" "$TMP/mk/templates"
  mutant="$TMP/mk/toolbelt/init.sh"
  awk '/^corpus_present\(\) \{/ { print "corpus_present() { return 1; }  # MUTANT: guard neutered"; next } { print }' "$SUT" > "$mutant"
  if ! grep -q 'MUTANT: guard neutered' "$mutant"; then
    no "teeth: could not build mutant (guard line not found)"
  else
    d="$TMP/teeth"; mkdir -p "$d"; printf 'REAL HAND-CURATED GAPS\n' > "$d/RESEARCH-STATE.md"
    bash "$mutant" "$d" --corpus flat >/dev/null 2>&1; mg=$?
    if [ "$mg" = 0 ] && ! grep -qF 'REAL HAND-CURATED GAPS' "$d/RESEARCH-STATE.md"; then
      ok "teeth: mutant clobbers curated state (exit 0, gone) → refuse tests have teeth"
    else
      no "teeth: mutant exit $mg / data present — refuse tests do NOT depend on the guard (THEATER)"
    fi
  fi

  # Mutation 2: neuter tools-README seeding — prove tools-scaffold assertions have teeth
  echo "-- teeth proof: omit tools-README cpf, expect README to be absent --"
  mkdir -p "$TMP/tt/toolbelt"; ln -sfn "$HERE/../../templates" "$TMP/tt/templates"
  tt_mutant="$TMP/tt/toolbelt/init.sh"
  awk '/cpf.*tools-README\.template\.md/ { next } { print }' "$SUT" > "$tt_mutant"
  if ! grep -qE 'cpf.*tools-README' "$SUT" || grep -qE 'cpf.*tools-README' "$tt_mutant"; then
    no "teeth: could not build tools-scaffold mutant (cpf line not found or not removed)"
  else
    dt="$TMP/tth"; mkdir -p "$dt"
    bash "$tt_mutant" "$dt" --corpus flat >/dev/null 2>&1
    if [ ! -f "$dt/tools/README.md" ]; then
      ok "teeth: mutant skipped tools/README.md → tools-scaffold tests have teeth"
    else
      no "teeth: mutant still produced tools/README.md — tools-scaffold tests are THEATER"
    fi
  fi

  # Mutation M1: strip (PROMPT-LOOP §b) from step-1 → §b) absent in stdout
  echo "-- teeth proof M1: strip (PROMPT-LOOP §b) from step-1 echo → §b) absent --"
  mkdir -p "$TMP/m1/toolbelt"; ln -sfn "$HERE/../../templates" "$TMP/m1/templates"
  m1_mutant="$TMP/m1/toolbelt/init.sh"
  awk '/\(PROMPT-LOOP §b\)/ { sub(/\(PROMPT-LOOP §b\)/, ""); } { print }' "$SUT" > "$m1_mutant"
  if grep -qF '(PROMPT-LOOP §b)' "$m1_mutant"; then
    no "teeth M1: could not build mutant ((PROMPT-LOOP §b) still present after strip)"
  else
    dm1="$TMP/m1t"; mkdir -p "$dm1"
    bash "$m1_mutant" "$dm1" --corpus flat > "$TMP/m1.out" 2>/dev/null
    if ! grep -qF "§b)" "$TMP/m1.out" 2>/dev/null; then
      ok "teeth M1: §b) absent after strip — step-1 cross-ref assertion has teeth"
    else
      no "teeth M1: §b) still present in mutant output — THEATER"
    fi
  fi

  # Mutation M2: always-print step-5 (remove prefix guard) → no-prefix ABSENT assertion flips red
  echo "-- teeth proof M2: remove prefix-if guard → step-5 appears in no-prefix run --"
  mkdir -p "$TMP/m2/toolbelt"; ln -sfn "$HERE/../../templates" "$TMP/m2/templates"
  m2_mutant="$TMP/m2/toolbelt/init.sh"
  awk '/if \[ -n "\$prefix" \]/ { print "if true; then  # MUTANT: always print step 5"; next } { print }' "$SUT" > "$m2_mutant"
  if ! grep -q 'MUTANT: always print step 5' "$m2_mutant"; then
    no "teeth M2: could not build mutant (prefix-if line not found)"
  else
    dm2="$TMP/m2t"; mkdir -p "$dm2"
    bash "$m2_mutant" "$dm2" --corpus flat > "$TMP/m2.out" 2>/dev/null
    if grep -qF "5. Block files use the prefix:" "$TMP/m2.out" 2>/dev/null; then
      ok "teeth M2: step-5 present in no-prefix mutant run — absent assertion has teeth"
    else
      no "teeth M2: step-5 NOT present in mutant run — absent assertion is THEATER"
    fi
  fi

  # Mutation M3: remove gitignored split line → gitignored/--force absent from already-git output
  echo "-- teeth proof M3: remove gitignored line → gitignored/--force absent --"
  mkdir -p "$TMP/m3/toolbelt"; ln -sfn "$HERE/../../templates" "$TMP/m3/templates"
  m3_mutant="$TMP/m3/toolbelt/init.sh"
  awk '/\.claude\/ hook is gitignored/ { next } { print }' "$SUT" > "$m3_mutant"
  if grep -qF '.claude/ hook is gitignored' "$m3_mutant"; then
    no "teeth M3: could not build mutant (gitignored line not removed)"
  else
    if ! command -v git >/dev/null 2>&1; then
      echo "  SKIP  teeth M3: git not on PATH"
    else
      dm3="$TMP/m3t"; mkdir -p "$dm3"; git -C "$dm3" init -q 2>/dev/null
      bash "$m3_mutant" "$dm3" --corpus flat > "$TMP/m3.out" 2>/dev/null
      if ! grep -qF "gitignored" "$TMP/m3.out" 2>/dev/null && ! grep -qF "git add --force" "$TMP/m3.out" 2>/dev/null; then
        ok "teeth M3: gitignored/--force absent in mutant output — already-git assertions have teeth"
      else
        no "teeth M3: gitignored or --force still present in mutant output — THEATER"
      fi
    fi
  fi

  # Mutation M4: delete NEXT echo line → research-sdd-status.sh absent from stdout
  echo "-- teeth proof M4: delete NEXT echo → research-sdd-status.sh absent --"
  mkdir -p "$TMP/m4/toolbelt"; ln -sfn "$HERE/../../templates" "$TMP/m4/templates"
  m4_mutant="$TMP/m4/toolbelt/init.sh"
  awk '/NEXT: run.*research-sdd-status\.sh/ { next } { print }' "$SUT" > "$m4_mutant"
  if grep -qF 'NEXT: run' "$m4_mutant"; then
    no "teeth M4: could not build mutant (NEXT echo line not removed)"
  else
    dm4="$TMP/m4t"; mkdir -p "$dm4"
    bash "$m4_mutant" "$dm4" --corpus flat > "$TMP/m4.out" 2>/dev/null
    if ! grep -qF "research-sdd-status.sh" "$TMP/m4.out" 2>/dev/null; then
      ok "teeth M4: research-sdd-status.sh absent in mutant output — next-step assertion has teeth"
    else
      no "teeth M4: research-sdd-status.sh still present in mutant output — THEATER"
    fi
  fi
fi

echo "== $pass passed · $fail failed =="
[ "$fail" -eq 0 ] || exit 1
