#!/usr/bin/env python3
"""Autogenerate CATALOG.md by scanning the sdd-mental-model-bloque*.md blocks.

Mirror of niagara-research/tools/gen-catalog.py: extracts the block number from
the file name and the title from the first `# Block N — ...` line.
Do NOT edit CATALOG.md by hand; regenerate with:  python3 tools/gen-catalog.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# ROOT via argv for symmetry with the kit generator (eje #2). This repo regenerates its OWN
# catalog with NO arg → parent.parent still resolves the repo root (backward-compatible).
ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent
BLOCK_RE = re.compile(r"^sdd-mental-model-bloque(\d+)\.md$")
TITLE_RE = re.compile(r"^#\s*(?:Block|Bloque)\s*\d+\s*[—-]\s*(.+?)\s*$")


def block_title(path: Path) -> str:
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith("# "):
                m = TITLE_RE.match(line)
                return m.group(1) if m else line[2:].strip()
    return "(untitled)"


def main() -> int:
    blocks: list[tuple[int, str, str]] = []
    for path in ROOT.glob("sdd-mental-model-bloque*.md"):
        m = BLOCK_RE.match(path.name)
        if not m:
            continue
        blocks.append((int(m.group(1)), path.name, block_title(path)))

    blocks.sort(key=lambda b: b[0])

    lines = [
        "<!-- AUTOGENERATED by tools/gen-catalog.py — DO NOT EDIT BY HAND. "
        "Regenerate: python3 tools/gen-catalog.py -->",
        "",
        "# Block catalog — gentle-ai SDD",
        "",
        f"Total: **{len(blocks)} blocks**",
        "",
        "| Block | File | Title |",
        "|-------|------|-------|",
    ]
    for num, fname, title in blocks:
        lines.append(f"| {num} | [{fname}]({fname}) | {title} |")
    lines.append("")

    out = ROOT / "CATALOG.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"CATALOG.md regenerated: {len(blocks)} blocks.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
