#!/usr/bin/env python3
"""Autogenerate CATALOG.md by scanning a corpus's `*-bloque*.md` blocks (Research-SDD).

Generic: detects any prefix (`<something>-bloqueN.md`), extracts the block number
from the file name and the title from the first `# Block N — ...` line.

Invocation-agnostic ROOT (eje #2 — ONE authority, not N synced copies):
  python3 <gen-catalog.py> <corpus-root>   # scan/write <corpus-root> — how research-sdd-archive drives it
  python3 <gen-catalog.py>                 # no arg → parent.parent (legacy per-target copy under <corpus>/tools/)
Do NOT edit CATALOG.md by hand; research-sdd (archive) regenerates it from the kit generator.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# ROOT via argv so ONE kit generator scans any corpus (eje #2: the recent case-sensitive BLOCK_RE
# change proved per-target COPIES drift → eliminate them). No arg → parent.parent keeps legacy
# per-target copies AND the repo's own catalog regen working (backward-compatible, both modes tested).
ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent
BLOCK_RE = re.compile(r"^(?P<prefix>.+)-(?:block|bloque)(?P<num>\d+)(?:-[\w-]+)?\.md$")
TITLE_RE = re.compile(r"^#\s*(?:Block|Bloque)\s*\d+\s*[—-]\s*(.+?)\s*$")


def block_title(path: Path) -> str:
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("# "):
                m = TITLE_RE.match(line.rstrip("\n"))
                return m.group(1) if m else line[2:].strip()
    return "(untitled)"


def main() -> int:
    blocks: list[tuple[int, str, str]] = []
    subject = ""
    for path in ROOT.glob("*.md"):
        m = BLOCK_RE.match(path.name)
        if not m:
            continue
        subject = subject or m.group("prefix")
        blocks.append((int(m.group("num")), path.name, block_title(path)))

    blocks.sort(key=lambda b: b[0])

    lines = [
        "<!-- AUTOGENERATED by research-sdd gen-catalog.py — DO NOT EDIT BY HAND. "
        "Regenerated by research-sdd-archive.sh (kit generator over the corpus root). -->",
        "",
        f"# Block catalog — {subject or '<subject>'}",
        "",
        f"Total: **{len(blocks)} blocks**",
        "",
        "| Block | File | Title |",
        "|-------|------|-------|",
    ]
    for num, fname, title in blocks:
        lines.append(f"| {num} | [{fname}]({fname}) | {title} |")
    lines.append("")

    (ROOT / "CATALOG.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"CATALOG.md regenerated: {len(blocks)} blocks.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
